# Generated by Django 4.1.2 on 2022-12-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='twitter_subs',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
