# Generated by Django 4.1.2 on 2022-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_twitter_link_player_twitter_subs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='twitter_link',
            new_name='twitch_link',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='twitter_subs',
            new_name='twitch_subs',
        ),
        migrations.AlterField(
            model_name='management',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
