# Generated by Django 4.1.2 on 2023-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_twitter_link_player_twitch_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitter_followers',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='vlr_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
